
services:
    app:
        build:
            context: .
            dockerfile: App.dockerfile
        ports:
            - "3000:8080"

        tty: true
        stdin_open: true
        command: /bin/bash



